services:
  debug-audio:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: debug-audio-dev
    ports:
      - "${EXTERNAL_PORT:-8069}:${INTERNAL_PORT:-80}"
    volumes:
      - ../src:/app/src:delegated
      - ../scripts:/app/scripts:delegated
      # Don't sync node_modules back to host
      - /app/node_modules
    environment:
      - PORT=${INTERNAL_PORT:-80}
    command: ["bun", "run", "dev"]
    restart: "no"
    stdin_open: true
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - augmentos-network-dev

networks:
  augmentos-network-dev:
    external: true
    name: augmentos-network-dev